//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGridView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTable
    {
        public int PersonID { get; set; }
        public string Saluation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string NIC { get; set; }
        public Nullable<System.DateTime> NIC_Validity { get; set; }
    }
}
